name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.16.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          level: warning
        continue-on-error: true

      - name: Setup Gradle 8.11.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1" # Quotes required to prevent YAML converting to number

      - name: Clean and Build
        run: gradle clean build -x test --no-daemon

      - name: Unit Test
        run: gradle test --no-daemon

      - name: Codecov Coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}